# Generated by Django 5.1 on 2025-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
