# Generated by Django 5.1.7 on 2025-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['created'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصویر ها'},
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['created'], name='blog_images_created_ae5d6b_idx'),
        ),
    ]
