# Generated by Django 5.1.7 on 2025-03-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_images_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='blog_image_created_1ba45b_idx',
            old_name='blog_images_created_ae5d6b_idx',
        ),
    ]
