# Generated by Django 5.1 on 2025-04-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0003_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.TextField(max_length=200),
        ),
    ]
