# Generated by Django 5.1 on 2025-04-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0004_alter_streamplatform_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watch_list.streamplatform'),
            preserve_default=False,
        ),
    ]
