# Generated by Django 5.1 on 2025-04-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0007_remove_review_user_name_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
