# Generated by Django 5.1 on 2025-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0008_alter_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
