# Generated by Django 5.1 on 2025-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0009_alter_watchlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.TextField(max_length=500),
        ),
    ]
